[debug] [2019-04-17T05:41:55.335Z] ----------------------------------------------------------------------
[debug] [2019-04-17T05:41:55.337Z] Command:       /usr/local/bin/node /Users/shinyzhang/.npm-global/bin/firebase login --reauth
[debug] [2019-04-17T05:41:55.337Z] CLI Version:   6.6.0
[debug] [2019-04-17T05:41:55.337Z] Platform:      darwin
[debug] [2019-04-17T05:41:55.337Z] Node Version:  v8.10.0
[debug] [2019-04-17T05:41:55.338Z] Time:          Wed Apr 17 2019 13:41:55 GMT+0800 (CST)
[debug] [2019-04-17T05:41:55.338Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=218427552&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2019-04-17T05:43:47.755Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  

[debug] [2019-04-17T05:45:03.589Z] Token Fetch Error: Error
    at new FirebaseError (/Users/shinyzhang/.npm-global/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/Users/shinyzhang/.npm-global/lib/node_modules/firebase-tools/lib/api.js:30:31)
    at self.callback (/Users/shinyzhang/.npm-global/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/Users/shinyzhang/.npm-global/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
